CREATE TABLE "GCG_6597_ORDERS_XREF"  (
 "ORDERWEBID" CHAR(25),
 "CUSTOMER" CHAR(8),
 "CUSTEXTID" CHAR(20),
 "ORDERNO" CHAR(20),
 "ORDERLINE" CHAR(5),
 "ORDDATE" DATE,
 "QTYORDERED" NUMERIC(8,4),
 "PARTNO" CHAR(20),
 "REV" CHAR(3),
 "LOC" CHAR(2),
 "LINEKEY" INTEGER,
 "LAST_FIN_STATUS" CHAR(20),
 "LINE_ITEM_ID" CHAR(25) );
