CREATE TABLE "GCG_6597_API" (
 "APIKEY" LONGVARCHAR,
 "APIPASS" LONGVARCHAR,
 "SINCE_DATE" DATE,
 "SHOPIFY_VER" VARCHAR(10),
 "REC_ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_REC_ID" UNIQUE USING 0,
 "LAST_PID" INTEGER,
 "LAST_RUN_TIME" DATETIME );
